### ISSUE TITLE
URL scheme?

### ISSUE THREAD

**Issue by josephj** [josephj/products-app#1]
One of the requirements is to use `react-router`. However I feel it's a bit odd since there is only one page. What's your expectation for the routing? 

The following is what I've implemented currently.

* `/products`
* All other routes will be redirected to `/products`

Ideas?

**Comment by whitechdevs** [comment]
You could use the react-router to catch any erroneous routes and either provide a 404 not found, or redirect. It is up to you.

**Comment by josephj** [comment]
Cool, I will just keep the current redirection behaviour.
