### ISSUE TITLE
Could you implement pagination as a horizontal bar?

### ISSUE THREAD

**Issue by whitechdevs** [josephj/products-app#2]
Please find the design here https://github.com/josephj/reactjs-test .

**Comment by josephj** [comment]
Sorry I missed out this request while I worked on it yesterday. I've achieved it using `react-js-paginate`. Let me know if you prefer to see a hand-craft one. :-)

**URL**
https://josephj.github.io/products-app/#/products

**Code Diff**
https://github.com/josephj/products-app/compare/a1875bc8f53960008883ba1b62145367ee8542d8...0c153f87510d29873df0c75e0425cffe02787d7f

**Screencast**
![image](https://user-images.githubusercontent.com/136648/51279359-48e1fb80-1a31-11e9-8077-bdccb35fe966.png)

**Comment by whitechdevs** [comment]
Sorry, I should have stated it before. Implementing it on your own would be great. Thanks.

**Comment by josephj** [comment]
@whitechdevs 

Done. I actually spent more time than expected on implement [getVisiblePages](https://github.com/josephj/products-app/pull/20/files#diff-b9b25c728f7b7d2a65eff1706124e1adR5) which helps me to find visible page range accordingly. I feel I haven't considered all the possible scenarios in my test. However, it should be enough while the `range` is always `3`.

https://github.com/josephj/products-app/pull/20
