### ISSUE TITLE
Review feedbacks

### ISSUE THREAD

**Issue by josephj** [josephj/products-app#22]
Most of the requirements are implemented. I will just stop here and let you to review it. 
https://github.com/josephj/products-app

Please let me know how you feel during the process. Thank you :D

**Comment by whitechdevs** [comment]
Hi Joseph,

Thanks for completing the test. We have had an internal review and are pleased with what you have produced. Arash should be reaching out to you to arrange for you to come in for a face to face.

Thanks,
Whitech Team
