### ISSUE TITLE
Ability to see different image states including loading and broken

### ISSUE THREAD

**Issue by josephj** [josephj/products-app#6]
Do you have any spec for the product image? There are several things in my mind. 

- Image broken handling?
- Responsiveness?
- Loading state

Currently it's 180x180 with the `object-fits: contain` (Also do I need to consider IE 11?). Let me know your expectation.

**Comment by whitechdevs** [comment]
Good question. We've intentionally left the product image spec vague to let the developer decide what would be best. 

To answer some of your questions:
- Image broken handling: yes it is important
- responsiveness: while there are a few ways to go about tackling this for images in regards to it being responsive, it is good enough that you have pointed it out. That being said, if you wish to tackle this, it will be considered a bonus.
- loading state: similarly to the above point re: responsiveness.
- IE11 compatibility: no need

**Comment by josephj** [comment]
The loading and broken image states are implemented
https://github.com/josephj/products-app/pull/7/files
https://josephj.github.io/products-app/#/products
